# Generated by Django 3.2.21 on 2023-09-24 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('added_to_cart', models.BooleanField(default=False)),
                ('discounted_price', models.FloatField()),
                ('producer', models.CharField(choices=[('LV', 'Louis Vuitton'), ('CK', 'Calvin Klein'), ('LC', 'Lacosta'), ('VS', 'Versace'), ('GV', 'Givenchy'), ('RX', 'Rolex'), ('SP', 'Supreme'), ('DG', 'Dolce and Gabanna'), ('HR', 'Hermes'), ('AD', 'Addidas'), ('FL', 'Fila'), ('GC', 'Gucci')], max_length=2)),
                ('description', models.TextField(default='')),
                ('category', models.CharField(choices=[('OT', 'Others'), ('BW', 'Baby Clothes'), ('CL', 'Clothes'), ('SH', 'Shoe'), ('BG', 'Bags')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_image', models.ImageField(upload_to='payment')),
                ('amount', models.FloatField()),
                ('paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
                ('receipt', models.ImageField(upload_to='receipt')),
                ('amount', models.FloatField(default=0)),
                ('payment_time', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, null=True)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Packed', 'Packed'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Accepted', 'Accepted'), ('On the Way', 'On the Way')], default='Pending', max_length=50, null=True)),
                ('payment', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.payapp')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Incart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ManyToManyField(to='app.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('EK', 'Ekiti'), ('LG', 'Lagos'), ('KO', 'Kano'), ('OY', 'Oyo'), ('JG', 'Jigawa'), ('EB', 'Ebonyi'), ('AD', 'Adamawa'), ('ON', 'Ondo'), ('PT', 'Plateau'), ('BY', 'Bayelsa'), ('AN', 'Anambra'), ('ED', 'Edo'), ('SK', 'Sokoto'), ('DT', 'Delta'), ('BN', 'Benue'), ('GB', 'Gombe'), ('OS', 'Osun'), ('TB', 'Taraba'), ('KW', 'Kwara'), ('YB', 'Yobe'), ('KN', 'Kano'), ('EN', 'Enugu'), ('AK', 'Akwa-ibom'), ('BR', 'Borno'), ('NS', 'Nassarawa'), ('BC', 'Bauchi'), ('KD', 'Kaduna'), ('KT', 'Kastina'), ('ZM', 'Zamfara'), ('IM', 'Imo'), ('NG', 'Niger'), ('KG', 'Kogi'), ('OG', 'Ogun'), ('KB', 'Kebbi'), ('RV', 'Rivers'), ('CR', 'Cross-River'), ('AB', 'Abia')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
