# Generated by Django 3.2.21 on 2023-09-28 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20230925_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='payapp',
            name='city',
            field=models.CharField(default='p', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payapp',
            name='email',
            field=models.EmailField(default='p@gmail.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('YB', 'Yobe'), ('PT', 'Plateau'), ('OS', 'Osun'), ('AK', 'Akwa-ibom'), ('KN', 'Kano'), ('TB', 'Taraba'), ('GB', 'Gombe'), ('AN', 'Anambra'), ('BY', 'Bayelsa'), ('OG', 'Ogun'), ('AB', 'Abia'), ('EB', 'Ebonyi'), ('LG', 'Lagos'), ('EK', 'Ekiti'), ('OY', 'Oyo'), ('ZM', 'Zamfara'), ('BN', 'Benue'), ('AD', 'Adamawa'), ('KD', 'Kaduna'), ('JG', 'Jigawa'), ('KG', 'Kogi'), ('RV', 'Rivers'), ('SK', 'Sokoto'), ('DT', 'Delta'), ('IM', 'Imo'), ('BC', 'Bauchi'), ('EN', 'Enugu'), ('ED', 'Edo'), ('CR', 'Cross-River'), ('BR', 'Borno'), ('KT', 'Kastina'), ('KB', 'Kebbi'), ('NS', 'Nassarawa'), ('NG', 'Niger'), ('KO', 'Kano'), ('ON', 'Ondo'), ('KW', 'Kwara')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('Pending', 'Pending'), ('On the Way', 'On the Way'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('Canceled', 'Canceled')], default='Pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('WS', 'Web Services'), ('OT', 'Others'), ('PS', 'Printing Services'), ('GD', 'Graphic design'), ('PF', 'Picture Frames')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.CharField(choices=[('LC', 'Lacosta'), ('DG', 'Dolce and Gabanna'), ('AD', 'Addidas'), ('GV', 'Givenchy'), ('SP', 'Supreme'), ('GC', 'Gucci'), ('VS', 'Versace'), ('FL', 'Fila'), ('CK', 'Calvin Klein'), ('HR', 'Hermes'), ('RX', 'Rolex'), ('LV', 'Louis Vuitton')], max_length=2),
        ),
        migrations.CreateModel(
            name='Paywhatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=20)),
                ('amount', models.FloatField(default=0)),
                ('email', models.EmailField(max_length=50)),
                ('payment_time', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
